### ISSUE TITLE
admin stuff

### ISSUE THREAD

**Issue by crazyduck2** [theindiepocalypse/abababababababab#1]

**Comment by theindiepocalypse** [comment]
@crazyduck2 Thanks for creating this issue

**Comment by crazyduck2** [comment]
@theindiepocalypse delete repo/

**Comment by theindiepocalypse** [comment]
@crazyduck2 only admins can delete a repository

**Comment by crazyduck2** [comment]
@theindiepocalypse list admins/

**Comment by theindiepocalypse** [comment]
@crazyduck2  @theindiepocalypse @skariel  are admins

**Comment by crazyduck2** [comment]
@theindiepocalypse list owners/

**Comment by theindiepocalypse** [comment]
@crazyduck2 

Owner | Percent
-------|---------
*total* | 100.0

**Comment by crazyduck2** [comment]
@theindiepocalypse merge/

**Comment by theindiepocalypse** [comment]
@crazyduck2 merging commands are allowed only on pull requests, nothing to merge here :)

**Comment by crazyduck2** [comment]
123

**Comment by crazyduck2** [comment]
@theindiepocalypse merge/

**Comment by theindiepocalypse** [comment]
@crazyduck2 merging commands are allowed only on pull requests, nothing to merge here :)

**Comment by crazyduck2** [comment]
@theindiepocalypse hi/

**Comment by theindiepocalypse** [comment]
@crazyduck2 hi!

**Comment by crazyduck2** [comment]
@theindiepocalypse hi

**Comment by theindiepocalypse** [comment]
@crazyduck2 such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse close

**Comment by theindiepocalypse** [comment]
@skariel: such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse deleter repo

**Comment by theindiepocalypse** [comment]
@skariel: such command... much help please

**Comment by skariel** [comment]
@theindiepocalypse delete repo
